server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-config
          uri: lb://customer-config
          predicates:
            - Path=/customer/**